### ISSUE TITLE
Consistent plugin name for updating/project compatibility

### ISSUE THREAD

**Issue by ThoughtPhotography** [sjoerdvankreel/infernal-synth#11]
Assuming most updates don't break backwards compatibility I think it would be helpful if the same filename was used.
That way we don't need to worry about keeping every 1.x version installed so they can be found by existing projects.

**Comment by sjoerdvankreel** [comment]
I fully agree, but unfortunately due to this https://forum.renoise.com/t/saved-automation-data-does-not-respect-vst3s-parameter-id/68461 it is almost impossible *not* to break at the slightest provocation of the source code. I currently work around that in infernal synth's successor https://github.com/sjoerdvankreel/firefly-synth/ by just not supporting renoise, but that's not a viable long-term solution. Have to think about this a bit more, I haven't come up with a good solution yet. But I understand having to keep version 1.0, 1.1, 1.2, 1.3 etc etc side-by-side is not ideal.

**Comment by sjoerdvankreel** [comment]
That was the exact solution I came up with previously. Although, I probably shouldn't have called it "versioned/unversioned". It sparked some hilarious discussion over here: https://audiosex.pro/threads/sjoerdvankreel-infernalsynth-was-anyone-able-to-get-this-to-work.69579/. 

And you're right btw, Renoise is my personal host of choice. ATM I only know of renoise that gets this wrong, but flstudio sufferered the same problem (they fixed it last year), but it goes to wonder who else gets this wrong.

Eventually I'll have to just bite the bullet again and start separate versioning for well-behaving and not-well-behaving hosts.
But it will be for firefly synth, not infernal.
