### ISSUE TITLE
Unable to save preset (context menu troubles).

### ISSUE THREAD

**Issue by MythosMusik** [sjoerdvankreel/infernal-synth#3]
I am currently using Waveform 11 Pro and Infernal-Synth 1.1.3.  When I click save preset, it goes into the default configuration it opens with.

**Comment by sjoerdvankreel** [comment]
Hey there. Thanks for taking the time to open this issue. I've run infernal synth in waveform pro and indeed I see the same behaviour. In fact, it's even worse: clicking any context menu item (not just save preset) resets the plugin to factory default. I've been debugging the source code and found that this is probably due to a fault at waveform's end. Unfortunately this is not something that I can easily work around so I have contacted Tracktion support in the hope they can clarify things a bit. In the meantime, would you be willing to test the load/save menu items with some other hosts? I've tested with renoise/FL Studio/Bitwig and REAPER. Those should at least work. Also most of them have a save-as preset built-in to the host should you want to play around with infernal and still be able to save the preset. 

Anyway i know this is probably not what you wanted to hear but either 1) there is a *big* bug in waveform or 2) i have *very much overlooked something* in case I'm hoping tracktion support will point me in the right direction. Will keep you posted.

-greets, Sjoerd

**Comment by sjoerdvankreel** [comment]
Well, how about that. The context menu (all of it) works just fine if you open it by ctrl+left-click instead of right-click. Thats a nice backdoor i built in there because i was having menu troubles on another host also.

**Comment by MythosMusik** [comment]
Thank you so much for the advice! Good luck with Tracktion.

**Comment by sjoerdvankreel** [comment]
Thanks. I take it it's working now, then?

**Comment by sjoerdvankreel** [comment]
Closing because I'm guessing it's working. Feel free to reopen.
